spring:
  rabbitmq:
    host: 192.168.1.101
    port: 5672
    username: lzh
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
hello:
  man: huayun007
