spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: lzh
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
hello:
  man: huayun009
